[package]
name = "oscli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]


[dependencies]
anyhow = "1.0.65"
clap = "4.0.10"
wgpu = "0.14.0"
cfg-if = "1"
winit = "0.27.1"
env_logger = "0.9"
log = "0.4"
pollster = "0.2"
rodio = "0.16.0"
cpal = "0.14.0"
symphonia = { version = "0.5.1", features = ["mp3"] }
minimp3 = "0.5.1"
lazy_static = "1.4.0"
rb = "0.3.2"